var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/engel/buchungen/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6a24789e._.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_1129957c._.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_e39990d7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c954261b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__96db3ed8._.js")
R.c("server/chunks/ssr/c32b7_next_dist_0f5fd2d2._.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_app_3973cde7._.js")
R.c("server/chunks/ssr/c32b7_next_dist_client_components_builtin_global-error_7b635e9f.js")
R.c("server/chunks/ssr/[root-of-the-server]__db68a3bb._.js")
R.c("server/chunks/ssr/c32b7_next_dist_client_components_d526182a._.js")
R.c("server/chunks/ssr/c32b7_next_dist_client_components_builtin_forbidden_16988068.js")
R.c("server/chunks/ssr/c32b7_next_dist_client_components_builtin_unauthorized_ad7e3a34.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_42ebfe73._.js")
R.c("server/chunks/ssr/609e6__next-internal_server_app_engel_buchungen_page_actions_c9b823e3.js")
R.m(93899)
module.exports=R.m(93899).exports
