// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/analytics" | "/admin/bookings" | "/admin/home" | "/admin/pflegebox" | "/admin/users" | "/auth/forgot-password" | "/auth/login" | "/auth/register" | "/auth/reset-password" | "/choose" | "/engel/bestaetigt/[id]" | "/engel/buchungen" | "/engel/chat" | "/engel/chat/[id]" | "/engel/dokumente" | "/engel/home" | "/engel/kalender" | "/engel/profil" | "/engel/register" | "/investor" | "/investor/pitch" | "/kunde/bestaetigt/[id]" | "/kunde/buchen/[id]" | "/kunde/buchungen" | "/kunde/chat" | "/kunde/chat/[id]" | "/kunde/dokumente" | "/kunde/engel/[id]" | "/kunde/home" | "/kunde/kalender" | "/kunde/karte" | "/kunde/pflegebox" | "/kunde/profil" | "/kunde/warten/[id]" | "/mis" | "/mis/ai-assistant" | "/mis/dataroom" | "/mis/documents" | "/mis/finance" | "/mis/market" | "/mis/quality" | "/mis/settings" | "/mis/supply-chain" | "/mis/team"
type AppRouteHandlerRoutes = "/api/admin/reset-password" | "/api/notify" | "/api/payment" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/engel" | "/kunde" | "/mis"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/bookings": {}
  "/admin/home": {}
  "/admin/pflegebox": {}
  "/admin/users": {}
  "/api/admin/reset-password": {}
  "/api/notify": {}
  "/api/payment": {}
  "/auth/callback": {}
  "/auth/forgot-password": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/reset-password": {}
  "/choose": {}
  "/engel": {}
  "/engel/bestaetigt/[id]": { "id": string; }
  "/engel/buchungen": {}
  "/engel/chat": {}
  "/engel/chat/[id]": { "id": string; }
  "/engel/dokumente": {}
  "/engel/home": {}
  "/engel/kalender": {}
  "/engel/profil": {}
  "/engel/register": {}
  "/investor": {}
  "/investor/pitch": {}
  "/kunde": {}
  "/kunde/bestaetigt/[id]": { "id": string; }
  "/kunde/buchen/[id]": { "id": string; }
  "/kunde/buchungen": {}
  "/kunde/chat": {}
  "/kunde/chat/[id]": { "id": string; }
  "/kunde/dokumente": {}
  "/kunde/engel/[id]": { "id": string; }
  "/kunde/home": {}
  "/kunde/kalender": {}
  "/kunde/karte": {}
  "/kunde/pflegebox": {}
  "/kunde/profil": {}
  "/kunde/warten/[id]": { "id": string; }
  "/mis": {}
  "/mis/ai-assistant": {}
  "/mis/dataroom": {}
  "/mis/documents": {}
  "/mis/finance": {}
  "/mis/market": {}
  "/mis/quality": {}
  "/mis/settings": {}
  "/mis/supply-chain": {}
  "/mis/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/engel": never
  "/kunde": never
  "/mis": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
