// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/bookings">> = Specific
  const handler = {} as typeof import("../../app/admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/home">> = Specific
  const handler = {} as typeof import("../../app/admin/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/pflegebox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pflegebox">> = Specific
  const handler = {} as typeof import("../../app/admin/pflegebox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/choose/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/choose">> = Specific
  const handler = {} as typeof import("../../app/choose/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/bestaetigt/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/bestaetigt/[id]">> = Specific
  const handler = {} as typeof import("../../app/engel/bestaetigt/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/buchungen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/buchungen">> = Specific
  const handler = {} as typeof import("../../app/engel/buchungen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/chat/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/chat/[id]">> = Specific
  const handler = {} as typeof import("../../app/engel/chat/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/chat">> = Specific
  const handler = {} as typeof import("../../app/engel/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/dokumente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/dokumente">> = Specific
  const handler = {} as typeof import("../../app/engel/dokumente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/home">> = Specific
  const handler = {} as typeof import("../../app/engel/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/kalender/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/kalender">> = Specific
  const handler = {} as typeof import("../../app/engel/kalender/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/profil">> = Specific
  const handler = {} as typeof import("../../app/engel/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engel/register">> = Specific
  const handler = {} as typeof import("../../app/engel/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor">> = Specific
  const handler = {} as typeof import("../../app/investor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investor/pitch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investor/pitch">> = Specific
  const handler = {} as typeof import("../../app/investor/pitch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/bestaetigt/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/bestaetigt/[id]">> = Specific
  const handler = {} as typeof import("../../app/kunde/bestaetigt/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/buchen/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/buchen/[id]">> = Specific
  const handler = {} as typeof import("../../app/kunde/buchen/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/buchungen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/buchungen">> = Specific
  const handler = {} as typeof import("../../app/kunde/buchungen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/chat/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/chat/[id]">> = Specific
  const handler = {} as typeof import("../../app/kunde/chat/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/chat">> = Specific
  const handler = {} as typeof import("../../app/kunde/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/dokumente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/dokumente">> = Specific
  const handler = {} as typeof import("../../app/kunde/dokumente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/engel/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/engel/[id]">> = Specific
  const handler = {} as typeof import("../../app/kunde/engel/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/home">> = Specific
  const handler = {} as typeof import("../../app/kunde/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/kalender/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/kalender">> = Specific
  const handler = {} as typeof import("../../app/kunde/kalender/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/karte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/karte">> = Specific
  const handler = {} as typeof import("../../app/kunde/karte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/pflegebox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/pflegebox">> = Specific
  const handler = {} as typeof import("../../app/kunde/pflegebox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/profil">> = Specific
  const handler = {} as typeof import("../../app/kunde/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/warten/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kunde/warten/[id]">> = Specific
  const handler = {} as typeof import("../../app/kunde/warten/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/ai-assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/ai-assistant">> = Specific
  const handler = {} as typeof import("../../app/mis/ai-assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/dataroom/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/dataroom">> = Specific
  const handler = {} as typeof import("../../app/mis/dataroom/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/documents">> = Specific
  const handler = {} as typeof import("../../app/mis/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/finance">> = Specific
  const handler = {} as typeof import("../../app/mis/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/market/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/market">> = Specific
  const handler = {} as typeof import("../../app/mis/market/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis">> = Specific
  const handler = {} as typeof import("../../app/mis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/quality/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/quality">> = Specific
  const handler = {} as typeof import("../../app/mis/quality/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/settings">> = Specific
  const handler = {} as typeof import("../../app/mis/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/supply-chain/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/supply-chain">> = Specific
  const handler = {} as typeof import("../../app/mis/supply-chain/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mis/team">> = Specific
  const handler = {} as typeof import("../../app/mis/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset-password">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notify">> = Specific
  const handler = {} as typeof import("../../app/api/notify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment">> = Specific
  const handler = {} as typeof import("../../app/api/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engel/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/engel">> = Specific
  const handler = {} as typeof import("../../app/engel/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kunde/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/kunde">> = Specific
  const handler = {} as typeof import("../../app/kunde/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mis/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/mis">> = Specific
  const handler = {} as typeof import("../../app/mis/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
