var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__604b53ab._.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_1129957c._.js")
R.c("server/chunks/ssr/c32b7_next_dist_bbf1c8e2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fb7343d6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__96db3ed8._.js")
R.c("server/chunks/ssr/c32b7_next_dist_0f5fd2d2._.js")
R.c("server/chunks/ssr/mnt_alltagsengel-app_app_3973cde7._.js")
R.c("server/chunks/ssr/372cd_alltagsengel-app__next-internal_server_app__global-error_page_actions_ca2e7ef9.js")
R.m(26729)
module.exports=R.m(26729).exports
